language: java
jdk:
  - oraclejdk8

deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
  skip_cleanup: true
  
addons:
  sonarcloud:
    organization: joseluisluri-github
    token:
      secure: $SONARCLOUD_TOKEN
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
